### PR TITLE
build for cjs and esm

### PR DESCRIPTION
**Pull request by jacobcoro**
Now this should be importable by node and browser, commonjs and es modules

### CODE REVIEW

**Comment by jacobcoro** [comment]
@YousefED Have you checked this out? The changes are pretty simple and straightforward. The failing test seems to be about a CI issue. Looks like time-out is not in the dependencies?

**Comment by YousefED** [comment]
Closing this in favor of https://github.com/YousefED/Matrix-CRDT/pull/14, what do you think? Does v0.0.6 also solve your issue?

**Comment by jacobcoro** [comment]
#15 working well with next.js! Thanks!

**Comment by jacobcoro** [comment]
@YousefED I spoke too soon. The new build was working in development but still failed in next.js local build and serve, and also in vercel's build

**Pull request closed without merging**
